/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.text.SimpleDateFormat;
import java.util.Date;
import log.ErrorLogger;
import net.Connector;
import net.MaintenanceMessage;

/**
 *
 * @author saf3
 */
public class MaintenancePane extends javax.swing.JPanel {
    private static SimpleDateFormat FORMAT = new SimpleDateFormat("dd/MM/yyyy/hh/mm");
    
    /**
     * Creates new form MaintenancePane
     */
    public MaintenancePane() {
        initComponents();
        
        //get time from server
        MaintenanceMessage msg = new MaintenanceMessage(Connector.getNextId());
        Connector.getSocket().sendMessage(msg);
        MaintenanceMessage reply = (MaintenanceMessage) 
                Connector.getSocket().receiveMessage();
        long millis = (Long) reply.getContent().get(MaintenanceMessage.TIME);
        Date date = new Date(millis);
        
        //put values into fields
        try {
            String dateString = FORMAT.format(date);
            String[] values = dateString.split("/");
            dayField.setText(values[0]);
            monthField.setText(values[1]);
            yearField.setText(values[2]);
            hoursField.setText(values[3]);
            minutesField.setText(values[4]);
        }
        catch(Exception e) {
            ErrorLogger.get().log(e.toString());
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        maintenanceTimeLabel = new javax.swing.JLabel();
        dayField = new javax.swing.JTextField();
        fwdSlash1 = new javax.swing.JLabel();
        monthField = new javax.swing.JTextField();
        fwdSlash2 = new javax.swing.JLabel();
        yearField = new javax.swing.JTextField();
        hoursField = new javax.swing.JTextField();
        colon = new javax.swing.JLabel();
        minutesField = new javax.swing.JTextField();
        changeButton = new javax.swing.JButton();
        feedback = new javax.swing.JLabel();

        maintenanceTimeLabel.setText("Maintenance Time (dd/mm/yyyy 24h format):");

        fwdSlash1.setText("/");

        fwdSlash2.setText("/");

        colon.setText(":");

        changeButton.setText("Change Maintenance Time");
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(dayField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fwdSlash1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fwdSlash2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hoursField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minutesField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(maintenanceTimeLabel)
                    .addComponent(changeButton)
                    .addComponent(feedback))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(maintenanceTimeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fwdSlash1)
                    .addComponent(monthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fwdSlash2)
                    .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoursField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(colon)
                    .addComponent(minutesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(changeButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(feedback)
                .addContainerGap(197, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        //change the maintenance time to the user's selection
        String dateString = dayField.getText() + "/" + monthField.getText() + "/" +
                yearField.getText() + "/" + hoursField.getText() + "/" +
                minutesField.getText();
        
        try {
            Date date = FORMAT.parse(dateString);
            MaintenanceMessage msg = new MaintenanceMessage(Connector.getNextId(),
                    date.getTime());
            Connector.getSocket().sendMessage(msg);
            feedback.setText("Time set.");
        }
        catch(Exception e) {
            ErrorLogger.get().log(e.toString());
            e.printStackTrace();
            feedback.setText("There has been an error in setting the maintenance time.");
        }
    }//GEN-LAST:event_changeButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton changeButton;
    private javax.swing.JLabel colon;
    private javax.swing.JTextField dayField;
    private javax.swing.JLabel feedback;
    private javax.swing.JLabel fwdSlash1;
    private javax.swing.JLabel fwdSlash2;
    private javax.swing.JTextField hoursField;
    private javax.swing.JLabel maintenanceTimeLabel;
    private javax.swing.JTextField minutesField;
    private javax.swing.JTextField monthField;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables
}
