package gui;

import java.util.HashMap;
import java.util.LinkedList;

/**
 * Class for viewing the results of a database search through a GUI.
 * It has a context-sensitive button that will change it's function
 * based on the table the view pane is displaying results from.
 * 
 * @author Stephen
 */
public class ViewPane extends javax.swing.JPanel {
    private TableEnum tableType;
    
    /**
     * Creates new form ViewPane
     */
    public ViewPane(TableEnum tableType) {
        initComponents();
        this.tableType = tableType;
        
        //table = tableType query result
        
        if(tableType.isButtonEnabled()) {
            contextButton.setText(tableType.getButtonText());
        }
        else {
            contextButton.setEnabled(false);
            contextButton.setVisible(false);
            contextPane.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contextPane = new javax.swing.JPanel();
        contextButton = new javax.swing.JButton();
        tablePane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(600, 380));

        contextPane.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        contextButton.setText("Context-Sensiitive Button");

        javax.swing.GroupLayout contextPaneLayout = new javax.swing.GroupLayout(contextPane);
        contextPane.setLayout(contextPaneLayout);
        contextPaneLayout.setHorizontalGroup(
            contextPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contextPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contextButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contextPaneLayout.setVerticalGroup(
            contextPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contextPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contextButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        table.setColumnSelectionAllowed(true);
        table.getTableHeader().setReorderingAllowed(false);
        tablePane.setViewportView(table);
        table.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contextPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tablePane, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tablePane, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contextPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contextButton;
    private javax.swing.JPanel contextPane;
    private javax.swing.JTable table;
    private javax.swing.JScrollPane tablePane;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Sets the contents to the given values.
     * 
     * @param contents List of maps of data, as generated by ResultMessage
     */
    public void setTableContents(LinkedList<HashMap<String, String>> contents) {
        //put contents from ResultMessage into table
    }
}
